#!/bin/bash

# chkconfig: 35 10 10
# description: Removed DNS entries from Route53
#

lockfile=/var/lock/updatednsroute53

case "$1" in
    start)
        /bin/bash /usr/sbin/update-dns-route53 1> /tmp/updatedns 2>&1
        touch $lockfile
        ;;
    stop)
        /usr/sbin/delete-dns-route53 1> /tmp/deletedns 2>&1
        rm -f $lockfile
        ;;
    status)
        if [[ -f $lockfile ]];
        then
          exit 0
        else
          exit 1
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
